
INSERT INTO DBO.TB_NIVEL(ID_NIVEL, NOMBRE)
VALUES( 1, 'PRIMARIA' );

INSERT INTO DBO.TB_NIVEL(ID_NIVEL, NOMBRE)
VALUES( 2, 'SECUNDARIA' );

GO

INSERT INTO DBO.TB_GRADO(ID_GRADO, ID_NIVEL, NOMBRE )
VALUES(101,1,'PRIMER GRADO');
INSERT INTO DBO.TB_GRADO(ID_GRADO, ID_NIVEL, NOMBRE )
VALUES(102,1,'SEGUNDO GRADO');
INSERT INTO DBO.TB_GRADO(ID_GRADO, ID_NIVEL, NOMBRE )
VALUES(103,1,'TERCER GRADO');
INSERT INTO DBO.TB_GRADO(ID_GRADO, ID_NIVEL, NOMBRE )
VALUES(104,1,'CUARTO GRADO');
INSERT INTO DBO.TB_GRADO(ID_GRADO, ID_NIVEL, NOMBRE )
VALUES(105,1,'QUINTO GRADO');
INSERT INTO DBO.TB_GRADO(ID_GRADO, ID_NIVEL, NOMBRE )
VALUES(106,1,'SEXTO GRADO');

INSERT INTO DBO.TB_GRADO(ID_GRADO, ID_NIVEL, NOMBRE )
VALUES(201,2,'PRIMER GRADO');
INSERT INTO DBO.TB_GRADO(ID_GRADO, ID_NIVEL, NOMBRE )
VALUES(202,2,'SEGUNDO GRADO');
INSERT INTO DBO.TB_GRADO(ID_GRADO, ID_NIVEL, NOMBRE )
VALUES(203,2,'TERCER GRADO');
INSERT INTO DBO.TB_GRADO(ID_GRADO, ID_NIVEL, NOMBRE )
VALUES(204,2,'CUARTO GRADO');
INSERT INTO DBO.TB_GRADO(ID_GRADO, ID_NIVEL, NOMBRE )
VALUES(205,2,'QUINTO GRADO');

GO

INSERT INTO DBO.TB_PERIODO( ID_PERIODO, INGRESO, PENSION, ESTADO )
VALUES( 2020, 1000.0, 1000.0, 1 );

INSERT INTO DBO.TB_PERIODO( ID_PERIODO, INGRESO, PENSION, ESTADO )
VALUES( 2021, 1100.0, 1100.0, 1 );

GO








