USE COLEGIO;
GO


INSERT INTO DBO.TB_ROLES(NOMBRE) VALUES('ADMINISTRADOR');
INSERT INTO DBO.TB_ROLES(NOMBRE) VALUES('OPERADOR');
GO



INSERT INTO DBO.TB_USUARIO(ID_ROL,NOMBRE,APELLIDO,USUARIO,CLAVE)
VALUES(1,'KARLA','GUZMAN0','KGUZMAN','123456');
GO


