
CREATE TABLE TB_TIPO_OBLIGACION
( 
	ID_TIPO              integer  NOT NULL ,
	NOMBRE               varchar(100)  NULL ,
	MORA                 numeric(10,2)  NOT NULL ,
	CONSTRAINT XPKTB_TIPO_OBLIGACION PRIMARY KEY (ID_TIPO ASC)
)
go



CREATE TABLE TB_OBLIGACION
( 
	ID_OBLIGACION        integer IDENTITY ( 1,1 ) ,
	NOMBRE               varchar(150)  NOT NULL ,
	ID_ESTUDIANTE        integer  NOT NULL ,
	ID_MATRICULA         integer  NULL ,
	ID_PERIODO           integer  NOT NULL ,
	ID_TIPO              integer  NOT NULL ,
	IMPORTE              numeric(10,2)  NOT NULL ,
	FECHA_VENC           datetime  NOT NULL ,
	ID_USUARIO           integer  NOT NULL ,
	CONSTRAINT XPKTB_OBLIGACION PRIMARY KEY (ID_OBLIGACION ASC),
	CONSTRAINT FK_OBLIGACION_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES dbo.TB_ESTUDIANTE(ID_ESTUDIANTE)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT FK_OBLIGACION_MATRICULA FOREIGN KEY (ID_MATRICULA) REFERENCES dbo.TB_MATRICULA(ID_MATRICULA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT FK_OBLIGACION_PERIODO FOREIGN KEY (ID_PERIODO) REFERENCES dbo.TB_PERIODO(ID_PERIODO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT FK_OBLIGACION_TIPO_OBLIGACION FOREIGN KEY (ID_TIPO) REFERENCES TB_TIPO_OBLIGACION(ID_TIPO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT FK_OBLIGACION_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES dbo.TB_USUARIO(ID_USUARIO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
go



CREATE TABLE TB_PAGO
( 
	ID_OBLIGACION        integer  NOT NULL ,
	FECHA_PAGO           datetime  NOT NULL ,
	IMPORTE              numeric(10,2)  NOT NULL ,
	MORA                 numeric(10,2)  NULL ,
	TOTAL                numeric(10,2)  NULL ,
	ID_USUARIO           integer  NOT NULL ,
	CONSTRAINT XPKTB_PAGO PRIMARY KEY (ID_OBLIGACION ASC),
	CONSTRAINT FK_PAGO_OBLIGACION FOREIGN KEY (ID_OBLIGACION) REFERENCES TB_OBLIGACION(ID_OBLIGACION)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT FK_PAGO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES dbo.TB_USUARIO(ID_USUARIO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
go


