USE COLEGIO
GO


CREATE PROCEDURE DBO.USP_GET_SECCIONES
(@PERIODO INT, @NIVEL INT, @GRADO INT)
AS
SELECT 
	S.ID_SECCION   SECCION,
	S.ID_PERIODO   PERIODO,
	N.NOMBRE       NIVEL,
	G.NOMBRE       GRADO,
	S.NOMBRE       NOMBRE,
	S.VACANTES     VACANTES,
	S.MATRICULADOS MATRICULADOS
FROM COLEGIO.DBO.TB_NIVEL N 
JOIN COLEGIO.DBO.TB_GRADO G ON N.ID_NIVEL = G.ID_NIVEL
JOIN COLEGIO.DBO.TB_SECCION S ON G.ID_GRADO = S.ID_GRADO
WHERE S.ID_PERIODO = @PERIODO
AND   N.ID_NIVEL = IIF(@NIVEL = 0, N.ID_NIVEL, @NIVEL)
AND   S.ID_GRADO = IIF(@GRADO = 0, S.ID_GRADO, @GRADO)
ORDER BY 1
GO


EXEC DBO.USP_GET_SECCIONES 2020, 1, 0
GO










